/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pragy
 */


import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
public class QuestionPaper extends javax.swing.JFrame {
    int right=0;
    int wrong=0;
    int count=0;
    String[] questions={"1.Calcitriol is the biologically active form of which among the following Vitamins?",
        "2.In genetics, the Reverse transcriptase helps in which among the following transcriptions?",
        "3.Which part of the Central Nervous System controls “reflex Actions” ?",
        "4.Stapes, the smallest and the lightest bone in human body, is the part of which organ ?",
        "5.Which among the following is not found in RNA?",
        "6.Which among the following cell organelles is essential for Cellular respiration?",
        "7.In Gymnosperms seeds are__________?",
        "8.Bile is collected in___________?",
        "9.Athlete’s Foot or Tinia Pedis is caused by which of the following ?",
        "10.Schizophrenia is an example of _________?",
        };
    String[] firstOption={"Vitamin B",
    "Single stranded DNA into double stranded DNA",
    "Mesencephalon",
    "Ear",
    "Adenine",
    "Endoplasmic Reticulum",
    "Always naked",
    "Liver",
    "Bacteria",
    "Allergy",
    };
    String[] secondOption={"Vitamin C",
    "Single stranded RNA into double stranded DNA",
    "Rhombencephalon",
    "Nose",
    "Guanine",
    "Golgi Body",
    "Always covered",
    "Gall Bladder",
    "Virus",
    "Mental Illness",};
    String[] thirdOption={"Vitamin D",
    "Single Stranded RNA into double stranded RNA",
    "Medulla oblongata",
    "Neck",
    "Thymine",
    "Mitochondrion",
    "Naked in some and covered in others",
    "Duodenum Canal",
    "Fungi",
    "Organic Degenerative Diseases"
    };
    String[] fourthOption={"Vitamin E",
    "Double Stranded DNA into single stranded RNA",
    "Spinal Chord",
    "Hand",
    "All of them",
    "Lysosomes",
    "Absent",
    "Spleen",
    "Protozoan",
    "None of the above"};
    String[] rightOption={"Vitamin D",
    "Single stranded RNA into double stranded DNA",
    "Spinal Chord",
    "Ear",
    "Thymine",
    "Mitochondrion",
    "Always naked",
    "Gall Bladder",
    "Fungi",
    "Mental Illness"};
    /**
     * Creates new form QuestionPaper
     */
    public QuestionPaper() {
        initComponents();
        setText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_grp1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        title_lbl = new javax.swing.JLabel();
        q1_lbl = new javax.swing.JLabel();
        a_btn = new javax.swing.JRadioButton();
        b_btn = new javax.swing.JRadioButton();
        c_btn = new javax.swing.JRadioButton();
        d_btn = new javax.swing.JRadioButton();
        submit_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title_lbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        title_lbl.setText("QUESTION PAPER");

        btn_grp1.add(a_btn);
        a_btn.setText("A");

        btn_grp1.add(b_btn);
        b_btn.setText("B");

        btn_grp1.add(c_btn);
        c_btn.setText("C");

        btn_grp1.add(d_btn);
        d_btn.setText("D");

        submit_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        submit_btn.setText("SUBMIT");
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(q1_lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(b_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(228, 228, 228)
                                .addComponent(title_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(258, 258, 258)
                                .addComponent(submit_btn)))
                        .addGap(0, 237, Short.MAX_VALUE))
                    .addComponent(a_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(c_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(d_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(title_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(q1_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(a_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(d_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(submit_btn)
                .addGap(91, 91, 91))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        // TODO add your handling code here:
        if(count < 10) {
            check();
       
          
        }
       
     
    }//GEN-LAST:event_submit_btnActionPerformed
public void setText()
{
    if(count<10)
    {
    q1_lbl.setText(questions[count]);
    a_btn.setText(firstOption[count]);
    b_btn.setText(secondOption[count]);
    c_btn.setText(thirdOption[count]);
    d_btn.setText(fourthOption[count]);
    }
    
}
public JRadioButton getSelectedRadioButton(ButtonGroup buttonGroup) 
{

    Enumeration<AbstractButton> abstractButtons = buttonGroup.getElements();
    JRadioButton radioButton = null;

    while (abstractButtons.hasMoreElements()) {
        radioButton = (JRadioButton) abstractButtons.nextElement();
        if (radioButton.isSelected()) {
            break;
        }
    }
    return radioButton;
}
public void check()
{
    JRadioButton b=getSelectedRadioButton(btn_grp1);
    if (b.getText()==rightOption[count])
    {
        JOptionPane.showMessageDialog(null, "Correct");
        right++;
        btn_grp1.clearSelection();
    }
    else if(b.getText()!=rightOption[count])
    {
        JOptionPane.showMessageDialog(null, "Wrong");
        wrong++;
        btn_grp1.clearSelection();
    }
    count++;
    
    setText();
       if(count==10)
        {
        JOptionPane.showMessageDialog(null, "Correct= "+right+" Wrong= "+(wrong));
        }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuestionPaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuestionPaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuestionPaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestionPaper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuestionPaper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton a_btn;
    private javax.swing.JRadioButton b_btn;
    private javax.swing.ButtonGroup btn_grp1;
    private javax.swing.JRadioButton c_btn;
    private javax.swing.JRadioButton d_btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel q1_lbl;
    private javax.swing.JButton submit_btn;
    private javax.swing.JLabel title_lbl;
    // End of variables declaration//GEN-END:variables
}
